### ISSUE TITLE
ember cordova:build: Splash/icon images not being sourced from config.xml for Android only

### ISSUE THREAD

**Issue by trumb1mj** [isleofcode/ember-cordova#216]
Ember: 2.10.0
Cordova: 6.4.0
ember-cordova: 0.3.11

When running `ember cordova:build --platform=android --environment=production --release`  splash and icon files are not being sourced from the config.xml.  Files in the config.xml are completely ignored and default cordova images are used.  Things work as expected in iOS.

I was forced to manually copy files like so:

`cp ember-cordova/cordova/res/screen/android/port-xhdpi.png ember-cordova/cordova/platforms/android/res/drawable-port-xhdpi/screen.png`

**Comment by reidab** [comment]
I ran into something similar, and it turned out to be an issue with cordova-android (https://github.com/apache/cordova-android/pull/343) that was fixed by upgrading cordova-android to 6.1.0.

**Comment by v3ss0n** [comment]
tried 
```
cordova platform update android@6.1.0 --save
cordova platform rm android
cordova platform add android
```
inside cordova folder but it is saying not cordova folder

**Comment by reidab** [comment]
Are you in the `ember-cordova` folder, or the `ember-cordova/cordova` folder. Those commands will only work in the second one. You should also be able to use the `ember cdv:platform` command from your ember app directory to do the same things.

**Comment by alexblom** [comment]
@v3ss0n : Can you comment on if @reidab's advice helped you out / is this issue persisting?

**Comment by v3ss0n** [comment]
i will give a try and let you guys know , thanks!

**Comment by alexblom** [comment]
Going to close this now, but please re-open if the issue persists.
